services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: temdas_backend
      POSTGRES_PASSWORD: "QIRD70O_02Gkw8_Z-X_pHAdNCtVdKBGQ"
    volumes:
      - temdas_backend_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "hfd_f6UAyMmTide4qGRhZY651pBcWllK"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: temdas_backend_test
      POSTGRES_PASSWORD: "hui7n482d2AXKV6QO6k4skcLSjXL6Wwa"
    volumes:
      - temdas_backend_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "ZvfST1cpGBViqKCr9cNsvnEqIs4dlVLg"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  temdas_backend_data:
  temdas_backend_test_data:
